trigger:
  batch: true
  branches:
    include:
      - "master"

pr:
  autoCancel: true
  branches:
    include:
      - "master"
      - "FAT25-Development"

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.17
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
